[package]
name = "tsumeshogi-solver"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfpn = { path = "./dfpn" }
shogi-converter = { path = "./shogi-converter" }
solver = { path = "./solver" }
csa = "1.0.2"
clap = { version = "3.1.1", features = ["derive"] }
thiserror = "1.0.30"
shogi_core = "0.1.4"
shogi_usi_parser = "0.1.0"
shogi_official_kifu = "0.1.1"

[profile.release]
lto = true
