[package]
name = "tsumeshogi-solver"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfpn = { path = "./dfpn" }
dfpn-extended = { path = "./dfpn-extended" }
shogi-converter = { path = "./shogi-converter" }
csa = "1.0.1"
clap = { version = "3.1.1", features = ["derive"] }
shogi = "0.12.2"
thiserror = "1.0.30"
yasai = { git = "https://github.com/sugyan/yasai", tag = "0.1.3" }

[profile.release]
lto = true
