[package]
name = "tsumeshogi-solver"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfpn = { path = "./dfpn" }
dfpn-extended = { path = "./dfpn-extended" }
shogi-converter = { path = "./shogi-converter" }
csa = "1.0.2"
clap = { version = "3.1.1", features = ["derive"] }
thiserror = "1.0.30"
yasai = { git = "https://github.com/sugyan/yasai", tag = "0.5.0", features = ["simd"] }
shogi_core = "0.1.4"
shogi_usi_parser = "0.1.0"

[profile.release]
lto = true
