[package]
name = "shogi-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csa = "1.0.1"
itertools = "0.10.1"
encoding_rs = "0.8.29"
nom = "7.1.0"
