[package]
name = "dfpn-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shogi = "0.11.0"
rand = { version = "0.8.4", features = ["small_rng"] }
