name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests for dfpn-solver
      run: cargo test --verbose -p dfpn-solver --lib
    - name: Run tests for shogi-converter
      run: cargo test --verbose -p shogi-converter --lib

  clippy_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: rustup component add clippy
    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy-main
        args: --all-features
    - name: Run clippy for dfpn-solver
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy-dfpn-solver
        args: --all-features --manifest-path ./dfpn-solver/Cargo.toml
    - name: Run clippy for shogi-converter
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy-shogi-converter
        args: --all-features --manifest-path ./shogi-converter/Cargo.toml
