name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests for dfpn
      run: cargo test --verbose -p dfpn --lib
    - name: Run tests for dfpn-extended
      run: cargo test --verbose -p dfpn-extended --lib

  clippy_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: rustup component add clippy
    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy-main
        args: --all-features
    - name: Run clippy for dfpn
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy-dfpn
        args: --all-features --manifest-path ./dfpn/Cargo.toml
    - name: Run clippy for dfpn-extended
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: clippy-dfpn-extended
        args: --all-features --manifest-path ./dfpn-extended/Cargo.toml
